- name: Example
  hosts: all
  gather_facts: false
  sources:
    - name: range
      ansible.eda.range:
        limit: 5
  rules:
    - name: r1
      condition: event.i == 1
      action:
        debug: